on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build --tag rinsuki/discord-timecard-bot:latest .
        env:
          DOCKER_BUILDKIT: 1
      - run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u rinsuki --password-stdin
          docker push rinsuki/discord-timecard-bot:latest
          docker logout
        name: Push to DockerHub