on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build --tag docker.pkg.github.com/rinsuki/discord-timecard-bot/app:latest .
        env:
          DOCKER_BUILDKIT: 1
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u rinsuki --password-stdin docker.pkg.github.com
          docker push docker.pkg.github.com/rinsuki/discord-timecard-bot/app:latest
          docker logout docker.pkg.github.com
        name: Push to GitHub Packages