on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: buildkit-cache
          key: v1
      - run: |
          buildctl build \
            --frontend=dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --import-cache type=local,src=./buildkit-cache \
            --export-cache type=local,dest=./buildkit-cache \
            --output type=docker,name=rinsuki/discord-timecard-bot | docker load
      - run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u rinsuki --password-stdin
          docker push rinsuki/discord-timecard-bot:latest
          docker logout
        name: Push to DockerHub