on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: Ubuntu-latest
    steps:
      - run: |
          docker run --name buildkit -d --privileged -p 1234:1234 moby/buildkit --addr tcp://0.0.0.0:1234
          sudo docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
        name: Setup BuildKit
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: buildkit-cache
          key: v1
      - run: python3 .github/workflows/buildkit-wrapper.py
        name: Build container
        env: 
          BUILDKIT_HOST: tcp://0.0.0.0:1234
      - run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u rinsuki --password-stdin
          docker push rinsuki/discord-timecard-bot:latest
          docker logout
        name: Push to DockerHub